# -*- coding: utf-8 -*-
"""2.3 datatypes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hx60IV721xYWjxBRu1yH-cXNYVgK-7VU
"""



"""basics data types in python
1. integer
2. float
3. complex
4. boolean
5. string
"""

# integers
a=8
print(a)

type(a)

# floating point
b=2.3
print(b)
type(b)

#complex numbers
c = 1 + 3j
print(c)
type(c)

"""Conversion of 1 data type to another"""



# int to float
x = 10
print(x)
type(x)

y = float(x)
 print(y)
 type(y)

# float to int
x= 5.88
print(x)
type(x)

y = int(x)

print(y)
type(y)

"""Boolean

  1. True
  2. false
"""

a = True
print(a)
type(a)

b = False
print(b)
type(b)

a=7<3
print(a)
type(a)

a=7>3
print(a)
type(a)

"""String"""

print("Machine Learning")

my_string = "machine learning"
print(my_string)
type(my_string)

print("Hello"*5)

"""Slicing

"""

my_string = "programming"

"""p r o g r a m m i n g

0 1 2 3 4 5 6 7 8 9 10
"""

print(my_string[1:5])

# step
print(my_string[0:10:2])

"""string concatenation"""

word_1="machine "
word_2="learninig"

print(word_1+ word_2)

