# -*- coding: utf-8 -*-
"""2.4 list tuple set dictionary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QiCO7sFTwNQQPGHTFlSmQdOPgKNWzOd8

Types of objects in python:

  1. mutable obj
  2. immutable obj

Immutable Objects

  1. int
  2. float
  3. string
  4. bool
  5. tuple

Mutable object

  1. list
  2. set
  3. dictionary

list
"""

# list should be included in square bracket
my_list = [1,2,3,4,5]
print(my_list)
type(my_list)

# lists can have multiple data types
my_list=[2,3,1.8,'English', True]
print(my_list)

"""lists are Mutable --> Changable"""

# add elements to a list
my_list=[2,3,1.8,'English', True]
my_list.append(6)
print(my_list)

"""indexing always start from zero"""

# print elements of a list using their index
print(my_list[0])
print(my_list[2])

# lists allow duplicate values
list_1 = [1,2,3,4,5,12,2,3]
print(list_1)

print(len(list_1))

#intiating an empty list
list_2 = []
print(list_2)

list_2.append(5)
print(list_2)

# delete an item in a list
list_2 = [2,3,1.8,'English',True, 6]
print(list_2)

del list_2[2]
print(list_2)

#join 2 lists

list_3 = [1,2,3,4,5]
list_4 = [6,7,8,9,10]

list_5= list_3 + list_4
print(list_5)

"""Tuple

"""

tuple_1 = (2,3,4,5)
print(tuple_1)
type(tuple_1)

# tuple allows multiple data types
tuple_2 =(1,2,3.5,'machine learning', False)
print(tuple_2)

# converting a list to a tuple

my_list = [3,4,5,6]
print(my_list)

my_tuple = tuple(my_list)
print(my_list)

print(my_tuple[0])
print(my_tuple[1])

"""tuples -> immutable --> unchangable"""

my_tuple.append(6)

print(len(my_tuple))

"""SET"""

# set --> Curly brackets
my_set = {1,2,3,4,5}
print(my_set)
type(my_set)

print(my_set[0])

#sets donot have index

#convert a list to a set
list_5 = [4,5,6,7,8]

x = set(list_5)
print(x)

# set does not allow duplicate values

set_3 = {1,2,3,4,5,1,2,3}
print(set_3)

"""dictionary

key-value pair
"""

my_dictionary = {'name':'david', 'age':30, 'country':'india'}
print(my_dictionary)
type(my_dictionary)

print(my_dictionary['name'])
print(my_dictionary['age'])
print(my_dictionary['country'])

#dicitonary does not allow duplicate values
dictionary_2 = {'name':'david', 'age':30, 'country':'india','name':'david', 'age':30, 'country':'india'}
print(dictionary_2)

